### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by ptoche** [koundy/ggplot_theme_Publication#1]
Thanks for sharing this nice theme!

In my system, I had to write `base_family="Helvetica"` with a capital letter, otherwise I was getting errors like: 

```
    Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
      polygon edge not found
    In addition: Warning message:
    In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
      no font could be found for family "helvetica"
```

**Comment by koundy** [comment]
I am not sure why this is happening. I found similar issues in the past with Helvetica font. I have changed the default font to sans now. Also, there was an issue that it's not plotting axes lines when used with ggplot2 version 2.1.0. That is also fixed now. Thanks for pointing out the issue

**Comment by ptoche** [comment]
I noticed the problem with the axis lines after posting, I was going to look for a solution. Thanks for the update! 👍
